version: '3.8'

services:
  nexus-db:
    image: mysql:8.0
    container_name: nexus-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexusreview
      TZ: Asia/Shanghai
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  nexus-redis:
    image: redis:6.2
    container_name: nexus-redis
    command: redis-server --requirepass 123321
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  nexus-kafka:
    image: apache/kafka:3.7.0
    container_name: nexus-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://nexus-kafka:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@nexus-kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CLUSTER_ID=nexusReviewClusterId

  nexus-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-backend
    environment:
      - API-KEY=${API_KEY}
      - TZ=Asia/Shanghai
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=nexus-kafka:9092
    ports:
      - "8081:8081"
    depends_on:
      - nexus-db
      - nexus-redis
      - nexus-kafka
    volumes:
      - ./nexus-frontend/html/nexusreview/imgs/:/usr/share/nginx/html/nexusreview/imgs/

  nexus-nginx:
    image: nginx:alpine
    container_name: nexus-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nexus-frontend/html:/usr/share/nginx/html
      - ./nexus-frontend/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nexus-backend

volumes:
  redis-data:
