  nexus-consul:
    image: hashicorp/consul:1.16
    container_name: nexus-consul
    ports:
      - "8500:8500"
    command: "agent -dev -client 0.0.0.0"
    networks:
      - nexus-network

  nexus-gateway:
    build:
      context: .
      dockerfile: nexus-gateway/Dockerfile
    container_name: nexus-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=nexus-consul
      - TZ=Asia/Shanghai
    networks:
      - nexus-network
    depends_on:
      - nexus-consul

  nexus-service-main:
    build:
      context: .
      dockerfile: nexus-service-main/Dockerfile
    container_name: nexus-service-main
    environment:
      - API-KEY=${API_KEY}
      - TZ=Asia/Shanghai
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=nexus-kafka:9092
      - SPRING_CLOUD_CONSUL_HOST=nexus-consul
    networks:
      - nexus-network
    depends_on:
      - nexus-db
      - nexus-redis
      - nexus-kafka
      - nexus-consul

  nexus-service-ai:
    build:
      context: .
      dockerfile: nexus-service-ai/Dockerfile
    container_name: nexus-service-ai
    environment:
      - API-KEY=${API_KEY}
      - TZ=Asia/Shanghai
      - SPRING_CLOUD_CONSUL_HOST=nexus-consul
    networks:
      - nexus-network
    depends_on:
      - nexus-consul

  nexus-nginx:
    image: nginx:alpine
    container_name: nexus-nginx
    ports:
      - "80:80"
    volumes:
      - ./nexus-frontend/html:/usr/share/nginx/html
      - ./nexus-frontend/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nexus-gateway
    networks:
      - nexus-network

  nexus-prometheus:
    image: prom/prometheus:latest
    container_name: nexus-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - nexus-network

  nexus-grafana:
    image: grafana/grafana:latest
    container_name: nexus-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - nexus-network
    depends_on:
      - nexus-prometheus

networks:
  nexus-network:
    driver: bridge
